### PR TITLE
Adding installation guide.

### LINKED ISSUE #114: Add installation instructions
Seems trivial but good to have

### PR DESCRIPTION
**Pull request by cmungall**
Fixes #114

### CODE REVIEW

**Review by ielis — APPROVED** [review]
Hi @cmungall

thank you very much for the PR!

If you do not mind, I changed the `.venv` to `venv` (I somewhat dislike the hidden folders and we do not track `venv` in `.gitignore`) and I recommend developers to upgrade `pip` before the installation.

Otherwise it looks good, thanks again!

**Comment by ielis** [comment]
@pnrobinson the CI action is failing because the notebook uses a relative path to a HPO JSON instead of the `OntologyStore` API of HPO toolkit (see [here](https://github.com/monarch-initiative/pyphetools/actions/runs/9008572648/job/24750960808?pr=115)).

Please use the `OntologyStore` everytime you work with HPO. It would probably be better to have `pyphetools.creation.TemplateImporter` take `hpotk.MinimalOntology` instead of a `str`.

**Comment by cmungall** [comment]
Thanks! No strong opinion on the dot (I am a poetry-head myself 😄 )

And yes I was wondering about the failing action

**Review by pnrobinson — APPROVED** [review]

**Comment by pnrobinson** [comment]
Adjust
```
hp_json = "../hp.json"
created_by="ORCID:0000-0002-0736-9199"
timporter = TemplateImporter(template=template, hp_json=hp_json, created_by=created_by)
```
in example file so that we do not need the local hp.json

**Comment by pnrobinson** [comment]
I updated the templates in phenopacket store.
@ielis One issue is that the templates reach out to the VariantValidator API for many variants. Sometimes there is a network issue and one needs to simply rerun the cell. This can cause the CI to fail even though the code is correct. Not sure if we want to keep this in the default CI or make this action optional.

**Comment by pnrobinson** [comment]
@ielis 
It is probably better to put the CI tests in this repo -- for phenopacket-store, after we have generated the phenopackets, there is no need to rerun the scripts unless we notice a mistake. Also, in this repository we can check in pickled versions of the variant-validator response, which will avoid network issues. Was there any reason to do this via phenopacket-store or would this also be OK?

**Comment by pnrobinson** [comment]
I think it is probably OK to run the tests locally. We do not need to worry about "old" notebooks or whatever, because we only re-run the phenopackets if there was a mistake in the data. I think it is probably best to remove the CI for now. We will need to rethink the entire pipeline soon, in order to rethink the HPO annotation pipeline, and I think a lot of stuff needs to be done, but we are testing the phenoapckets with ppt etc etc. @ielis

**Comment by ielis** [comment]
Then I will drop the notebook action and I will deal with the network-dependent tests in #117

**Pull request merged**
