### PR TITLE
Added ability to use FastHPOCR instead of exact string matching. Refa…

### PR DESCRIPTION
**Pull request by tudorgroza**
…ctored HPOConceptRecognizer inheritance. Added data and tests.

### CODE REVIEW

**Review by pnrobinson — CHANGES_REQUESTED** [review]
For some reason, this is crashing on my end -- it is not finding the module: 
ImportError while importing test module '/Users/robin/GIT/pyphetools/test/test_vital_status.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test/test_vital_status.py:2: in <module>
    from pyphetools.creation import AgeOfDeathColumnMapper, Individual, MetaData
src/pyphetools/__init__.py:2: in <module>
    from . import creation
src/pyphetools/creation/__init__.py:10: in <module>
    from .create_template import TemplateCreator
src/pyphetools/creation/create_template.py:4: in <module>
    from .hpo_parser  import HpoParser
src/pyphetools/creation/hpo_parser.py:8: in <module>
    from .hpo_fasthpocr_cr import HpoFastHPOCRConceptRecognizer
src/pyphetools/creation/hpo_fasthpocr_cr.py:3: in <module>
    from FastHPOCR.HPOAnnotator import HPOAnnotator
E   ModuleNotFoundError: No module named 'FastHPOCR'
________________ ERROR collecting test/test_vital_status.py _________________
ImportError while importing test module '/Users/robin/GIT/pyphetools/test/test_vital_status.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test/test_vital_status.py:2: in <module>
    from pyphetools.creation import AgeOfDeathColumnMapper, Individual, MetaData
src/pyphetools/__init__.py:2: in <module>
    from . import creation
src/pyphetools/creation/__init__.py:10: in <module>
    from .create_template import TemplateCreator
src/pyphetools/creation/create_template.py:4: in <module>
    from .hpo_parser  import HpoParser
src/pyphetools/creation/hpo_parser.py:8: in <module>
    from .hpo_fasthpocr_cr import HpoFastHPOCRConceptRecognizer
src/pyphetools/creation/hpo_fasthpocr_cr.py:3: in <module>
    from FastHPOCR.HPOAnnotator import HPOAnnotator
E   ModuleNotFoundError: No module named 'FastHPOCR'
========================== short test summary info ==========================
ERROR src/pyphetools/__init__.py
ERROR src/pyphetools/creation/__init__.py
ERROR src/pyphetools/creation/create_template.py
ERROR src/pyphetools/creation/disease_id_column_mapper.py
ERROR src/pyphetools/creation/hpo_fasthpocr_cr.py
ERROR src/pyphetools/creation/hpo_parser.py
ERROR src/pyphetools/creation/import_template.py
ERROR src/pyphetools/creation/option_column_mapper.py
ERROR src/pyphetools/creation/scm_generator.py
ERROR src/pyphetools/creation/structural_variant.py
ERROR src/pyphetools/creation/thresholded_column_mapper.py

**Comment by tudorgroza** [comment]
Did you install the module?

**Comment by pnrobinson** [comment]
sorry it was very early in the morning, all is ok. Part of the CI is not building but that is not related to this PR so I will merge

**Comment by tudorgroza** [comment]
Thank you.

**Pull request merged**
